version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/django.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    # command: sh /code/docker_django_startup.sh
  db:
    image: postgres
    build:
      dockerfile: ./docker/postgres.Dockerfile
    environment:
      - POSTGRES_USER=mugunga
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_DB=sandbox
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: